title: VarelaMar Website
description: Exploring intercultural communication and digital literacy
theme: jekyll-theme-cayman

include:
  - home.html
  - glossary.html
  - workscited.html
  - rhetoric.html
  - assets/
