title: VarelaMar Website
remote_theme: pages-themes/cayman@v0.2.0
include:
  - index.html
  - resume.html
  - publishedWorks.html
  - infographics.html
  - assets
  - academicWriting.html
  - writingSamples.html
