title: VarelaMar Website
description: My GitHub Pages site with Cayman theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
include:
  - home.html
  - glossary.html
  - workcited.html
  - rhetoric.html
  - assets/
