theme: jekyll-theme-cayman
title: VarelaMar Website
description: Exploring intercultural communication and digital literacy

include:
  - home.html
  - glossary.html
  - workscited.html
  - rhetoric.html
  - assets/
