title: VarelaMar Website
description: Intercultural Communication and Hypertext
remote_theme: pages-themes/cayman@v0.2.0
include:
  - index.html
  - glossary.html
  - rhetoric.html
  - workcited.html
  - assets
  - digitalliteracyandrhetoric.html
  - cultureandtranslation.html
